"""SkyPilot launch-spec rendering + dry-run.

A cloud worker is *cattle, not a pet*: it clones the repo at an exact git SHA,
``uv sync``s, runs one declared experiment/sweep shard, uploads results, and
dies. We deliberately do NOT use SkyPilot's ``workdir`` upload — that would risk
shipping local/private data to a worker. Code travels via git@SHA only.

``--dry-run`` renders the exact YAML + commands and spends nothing. A real
launch additionally requires the budget preflight to pass AND an explicit
``--yes`` (and the ``[cloud]`` extra installed).
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Any

PROVIDER_TO_CLOUD = {"runpod": "runpod", "lambda": "lambda", "modal": "modal"}
GPU_TO_ACCEL = {"a10": "A10", "l4": "L4", "rtx4090": "RTX4090", "l40s": "L40S", "a10g": "A10G", "a40": "A40", "a100": "A100", "a100-80gb": "A100-80GB", "h100": "H100"}


@dataclass
class LaunchSpec:
    experiment: str
    overrides: list[str]
    provider: str = "runpod"
    gpu: str = "l40s"
    num_gpus: int = 1
    git_sha: str = "unknown"
    repo_url: str = "${GUARDIAN_REPO_URL}"
    sweep_name: str | None = None
    sweep_axes: dict[str, list[Any]] = field(default_factory=dict)
    seeds: list[int] = field(default_factory=lambda: [0])
    hours_per_job: float = 0.25

    def grid_size(self) -> int:
        n = 1
        for v in self.sweep_axes.values():
            n *= max(1, len(v))
        return n * max(1, len(self.seeds))


def _expand_commands(spec: LaunchSpec, limit: int | None = None) -> list[str]:
    """Expand the sweep into explicit `ga train` commands (illustrative for dry-run)."""
    device_override = "device=cuda" if spec.gpu.lower() != "cpu" else ""
    base = " ".join(filter(None, ["uv run ga train", f"+exp={spec.experiment}", *spec.overrides, device_override]))
    if not spec.sweep_axes:
        return [f"{base} seed={s}" for s in spec.seeds]
    # Cartesian product over axes x seeds.
    import itertools

    keys = list(spec.sweep_axes.keys())
    value_lists = [spec.sweep_axes[k] for k in keys]
    cmds = []
    for combo in itertools.product(*value_lists):
        axis_str = " ".join(f"{k}={v}" for k, v in zip(keys, combo, strict=True))
        for s in spec.seeds:
            cmds.append(f"{base} {axis_str} seed={s}")
            if limit and len(cmds) >= limit:
                return cmds
    return cmds


def _gcs_file_mounts() -> str:
    key_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "")
    if key_path and os.path.isfile(key_path):
        return f"file_mounts:\n  /gcs_key.json: {key_path}"
    return ""


def _render_one_task(name: str, spec: LaunchSpec, run_cmd: str) -> str:
    """Render a SkyPilot task YAML for a single grid-point command."""
    cloud = PROVIDER_TO_CLOUD.get(spec.provider, spec.provider)
    accel = GPU_TO_ACCEL.get(spec.gpu.lower(), spec.gpu.upper())
    return f"""# Auto-generated by `ga launch` — DO NOT hand-edit a running worker.
# Stateless worker: clone @SHA, uv sync, run one shard, upload, die.
name: {name}

resources:
  cloud: {cloud}
  accelerators: {accel}:{spec.num_gpus}

{_gcs_file_mounts()}
envs:
  GUARDIAN_REPO_URL: "{spec.repo_url}"
  GIT_SHA: {spec.git_sha}
  GUARDIAN_ARTIFACT_URI: "{os.environ.get('GUARDIAN_ARTIFACT_URI', '')}"

setup: |
  set -euo pipefail
  git clone "$GUARDIAN_REPO_URL" repo
  cd repo
  git checkout "$GIT_SHA"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
  uv sync
  # PyPI torch is CPU-only; swap in a CUDA build matching the worker's driver.
  # Lambda A10s ship driver 570.x (CUDA 12.8), so use cu128 index.
  # After the swap, set UV_NO_SYNC so `uv run` won't revert to the CPU wheel.
  if command -v nvidia-smi &>/dev/null; then
    nvidia-smi
    uv pip install torch --index-url https://download.pytorch.org/whl/cu128 --no-deps --reinstall
    export UV_NO_SYNC=1
    uv run python -c "import torch; print(f'CUDA OK: {{{{torch.cuda.get_device_name(0)}}}} | torch={{{{torch.__version__}}}}')"
  fi
  # GCS auth: if a service account key is mounted, activate it.
  if [ -f /gcs_key.json ]; then
    gcloud auth activate-service-account --key-file=/gcs_key.json 2>/dev/null || true
  fi

run: |
  set -euo pipefail
  cd repo
  export PATH="$HOME/.local/bin:$PATH"
  export UV_NO_SYNC=1
  export GUARDIAN_REPO_ROOT="$PWD"
  {run_cmd}
  # Upload results home, else they die with the worker. Per-SHA prefix so the
  # control plane can `ga collect --from $GUARDIAN_ARTIFACT_URI --sha $GIT_SHA`.
  if [ -n "$GUARDIAN_ARTIFACT_URI" ]; then
    dest="$GUARDIAN_ARTIFACT_URI/$GIT_SHA/runs/"
    echo "uploading runs/ -> $dest"
    case "$GUARDIAN_ARTIFACT_URI" in
      s3://*)  aws s3 sync runs/ "$dest" ;;
      gs://*)  gsutil -m rsync -r runs/ "$dest" ;;
      *)       mkdir -p "$dest" 2>/dev/null || true; rsync -az runs/ "$dest" ;;
    esac
  else
    echo "WARNING: GUARDIAN_ARTIFACT_URI unset — results will be LOST when this worker dies."
  fi
"""


def render_shard_yamls(spec: LaunchSpec) -> list[tuple[str, str]]:
    """Render one SkyPilot task YAML per grid point for parallel execution.

    Returns a list of (task_name, yaml_text) tuples.
    """
    cmds = _expand_commands(spec)
    base_name = f"guardian-{spec.experiment}" + (f"-{spec.sweep_name}" if spec.sweep_name else "")
    results = []
    for i, cmd in enumerate(cmds):
        name = f"{base_name}-{i:02d}"
        results.append((name, _render_one_task(name, spec, cmd)))
    return results


def render_task_yaml(spec: LaunchSpec) -> str:
    """Render a single combined task YAML (all shards serial). Used for dry-run display."""
    shards = render_shard_yamls(spec)
    if len(shards) == 1:
        return shards[0][1]
    # For display purposes, show first shard as representative.
    return shards[0][1]


def dry_run_text(spec: LaunchSpec, est_per_job: float, est_total: float, max_cost_usd: float) -> str:
    cmds = _expand_commands(spec)
    preview = "\n".join(f"    {c}" for c in cmds[:5])
    more = f"\n    ... (+{len(cmds) - 5} more)" if len(cmds) > 5 else ""
    return f"""
=== DRY RUN (no resources launched, no money spent) ===
provider           : {spec.provider}
accelerator        : {GPU_TO_ACCEL.get(spec.gpu.lower(), spec.gpu)} x{spec.num_gpus}
experiment         : {spec.experiment}
sweep              : {spec.sweep_name or '(single run)'}
git SHA            : {spec.git_sha}
grid size (jobs)   : {spec.grid_size()}
execution          : parallel (one VM per grid point)
est. cost / job    : ${est_per_job:.2f}
est. total cost    : ${est_total:.2f}
declared max cost  : ${max_cost_usd:.2f}

--- commands (one per VM, all launched in parallel) ---
{preview}{more}

--- representative SkyPilot task YAML (shard 0) ---
{render_task_yaml(spec)}
To actually launch (spends money), re-run WITHOUT --dry-run and add --yes.
A budget preflight + clean-tree + exact-SHA + dry-run-first check must pass.
""".rstrip()
